server:
  port: 8080

spring:
  application:
    name: speed-way
  datasource:
    url: jdbc:mysql://localhost:3306/speedway?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 0218
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新表结构
    show-sql: true  # 控制台显示SQL
    properties:
      hibernate:
        format_sql: true  # 格式化SQL输出
